// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqxSF-EIZe7KPw82LT4P1lEJJ30n3reAo',
    appId: '1:50771002944:web:7f4e4422ae708502c7c1a5',
    messagingSenderId: '50771002944',
    projectId: 'gih-user-side',
    authDomain: 'gih-user-side.firebaseapp.com',
    storageBucket: 'gih-user-side.appspot.com',
    measurementId: 'G-71MN39EWNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-MmjPMFZS-nA_XXwPyNoUUZq7JJQHbAg',
    appId: '1:50771002944:android:07935959d80bc405c7c1a5',
    messagingSenderId: '50771002944',
    projectId: 'gih-user-side',
    storageBucket: 'gih-user-side.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA9icl8JxEMbmqrl6cJ5DQxMLdi0HmnBM',
    appId: '1:50771002944:ios:c17b03543c724b51c7c1a5',
    messagingSenderId: '50771002944',
    projectId: 'gih-user-side',
    storageBucket: 'gih-user-side.appspot.com',
    androidClientId: '50771002944-fcrdhc75j2ku7vemtun7fpq963rnpsim.apps.googleusercontent.com',
    iosClientId: '50771002944-d9h6qm11qr1bt7eo24kupo89iqd4hfef.apps.googleusercontent.com',
    iosBundleId: 'com.example.gih',
  );
}
